services:
  - type: web
    name: disease-prediction-system
    env: python
    region: singapore
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
      build-essential \
      python3-dev \
      libcairo2 \
      libcairo2-dev \
      libpango-1.0-0 \
      libpango1.0-dev \
      libpangocairo-1.0-0 \
      libgdk-pixbuf2.0-0 \
      libgdk-pixbuf2.0-dev \
      libffi-dev \
      shared-mime-info \
      libcairo-gobject2 \
      libpangoft2-1.0-0 \
      && pip install --upgrade pip setuptools wheel \
      && pip install --only-binary :all: numpy==1.23.5 pandas==1.5.3 scikit-learn==1.3.0 \
      && pip install --no-cache-dir -r requirements.txt \
      && chmod -R 755 Data MasterData templates static
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL
        value: "True"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 