services:
  - type: web
    name: disease-prediction-system
    env: python
    region: singapore
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
      libcairo2-dev \
      libpango1.0-dev \
      libgdk-pixbuf2.0-dev \
      libffi-dev \
      shared-mime-info \
      && pip install --upgrade pip \
      && pip install --only-binary :all: numpy pandas scikit-learn \
      && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --chdir api index:app --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL
        value: "True"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 